collections:
  persons:
    output: true
    permalink: /:collection/:path/
  publications:
    output: false
  theses:
    output: false
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: persons # select all person pages
    values:
      layout: person
  - scope:
      path: ""
      type: projects # select all project pages
    values:
      layout: project
