FROM ruby

RUN gem install bundler jekyll jekyll-postcss

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt install nodejs

VOLUME [ "/app" ]
EXPOSE 4000
WORKDIR /app
ENTRYPOINT [ "/bin/sh", "-c", "npm install && bundle install && JEKYLL_ENV=staging bundle exec jekyll serve -H 0.0.0.0 --force_polling --livereload --verbose" ]
