FROM ruby

RUN gem install bundler jekyll

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt install nodejs

VOLUME [ "/app" ]
EXPOSE 4000
WORKDIR /app
ENTRYPOINT [ "/bin/sh", "-c", "npm install && bundle install && npm run dev" ]
