FROM ruby

RUN gem install bundler jekyll

VOLUME [ "/app" ]
EXPOSE 4000
WORKDIR /app
ENTRYPOINT [ "/bin/sh", "-c", "bundle install && bundle exec jekyll serve -H 0.0.0.0 --force_polling --livereload" ]
